# Generated by Django 4.1.5 on 2023-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0002_remove_grocerylist_groceries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery'), ('FROZEN', 'Frozen'), ('CONDIMENT', 'Condiment'), ('BEVERAGE', 'Beverage'), ('ALCOHOL', 'Alcohol'), ('PANTRY', 'Pantry'), ('MEAT', 'Meat'), ('DELI', 'Deli')], default='UNCATEGORIZED', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='February 08 2023', max_length=100, unique=True),
        ),
    ]
