# Generated by Django 4.1.5 on 2023-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0003_groceryitem_category_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery'), ('FROZEN', 'Frozen'), ('CONDIMENT', 'Condiment'), ('BEVERAGE', 'Beverage'), ('ALCOHOL', 'Alcohol'), ('PANTRY', 'Pantry'), ('MEAT', 'Meat'), ('DELI', 'Deli')], default='UNCATEGORIZED', max_length=200),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='March 06 2023', max_length=100, unique=True),
        ),
    ]
