# Generated by Django 4.1.5 on 2023-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0004_alter_groceryitem_category_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='March 07 2023', max_length=100, unique=True),
        ),
    ]
