# Generated by Django 4.1.5 on 2023-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0005_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='March 19 2023', max_length=100, unique=True),
        ),
    ]
