# Generated by Django 4.1.5 on 2023-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0008_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery'), ('FROZEN', 'Frozen'), ('CONDIMENT', 'Condiment'), ('BEVERAGE', 'Beverage'), ('ALCOHOL', 'Alcohol'), ('PANTRY', 'Pantry'), ('MEAT', 'Meat'), ('DELI', 'Deli'), ('HOUSEHOLD', 'Household'), ('PET', 'Pet'), ('WELLNESS', 'Wellness'), ('BEAUTY', 'Beauty')], default='UNCATEGORIZED', max_length=200),
        ),
    ]
