# Generated by Django 4.1.5 on 2023-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0009_alter_groceryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='April 02 2023', max_length=100, unique=True),
        ),
    ]
