# Generated by Django 4.1.5 on 2023-08-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0014_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='August 24 2023', max_length=100, unique=True),
        ),
    ]
