# Generated by Django 4.1.5 on 2023-09-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_lists', '0016_alter_grocerylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('ALCOHOL', 'Alcohol'), ('BAKERY', 'Bakery'), ('BEAUTY', 'Beauty'), ('BEVERAGE', 'Beverage'), ('CONDIMENT', 'Condiment'), ('DAIRY', 'Dairy'), ('DELI', 'Deli'), ('FROZEN', 'Frozen'), ('PANTRY', 'Pantry'), ('PRODUCE', 'Produce'), ('HOUSEHOLD', 'Household'), ('PET', 'Pet'), ('MEAT', 'Meat'), ('WELLNESS', 'Wellness')], default='UNCATEGORIZED', max_length=200),
        ),
    ]
