# Generated by Django 4.1.5 on 2023-03-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipe_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
