# Generated by Django 4.1.5 on 2023-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
